.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -382,46 +382,46 @@ jobs:
   release_packages:
     environment:
       <<: *ENVIRONMENT
-      docker: *packet_exec
-      steps:
-        - attach_workspace:
-            at: .
-        - run:
-            name: Release Vagrant Packages
-            command: |
-              set +e
-              rm -f ./assets/substrate*
-              export AWS_ACCESS_KEY_ID="${AWS_RELEASE_ID}"
-              export AWS_SECRET_ACCESS_KEY="${AWS_RELEASE_KEY}"
-              echo "Uploading to the releases site..."
-              hc-releases upload ./assets > .output 2>&1 &
-              pid=$!
-              until [ -f .output ]; do
-                sleep 0.1
-              done
-              tail -f --quiet --pid $pid .output
-              wait $pid
-              rm .output
-              result=$?
-              if [ $result -ne 0 ]; then
-                slack -s error -m "Failed to upload new release!" -f .output -T 5
-                exit 1
-              fi
-              echo "Publishing new release..."
-              hc-releases publish > .output 2>&1 &
-              pid=$!
-              until [ -f .output ]; do
-                sleep 0.1
-              done
-              tail -f --quiet --pid $pid .output
-              wait $pid
-              rm .output
-              result=$?
-              if [ $result -ne 0 ]; then
-                slack -s error -m "Failed to publish release!" -f .output -T 5
-                exit 1
-              fi
-              slack -m "New Vagrant release has been published! - *${CIRCLE_TAG}*"
+    docker: *packet_exec
+    steps:
+      - attach_workspace:
+          at: .
+      - run:
+          name: Release Vagrant Packages
+          command: |
+            set +e
+            rm -f ./assets/substrate*
+            export AWS_ACCESS_KEY_ID="${AWS_RELEASE_ID}"
+            export AWS_SECRET_ACCESS_KEY="${AWS_RELEASE_KEY}"
+            echo "Uploading to the releases site..."
+            hc-releases upload ./assets > .output 2>&1 &
+            pid=$!
+            until [ -f .output ]; do
+              sleep 0.1
+            done
+            tail -f --quiet --pid $pid .output
+            wait $pid
+            rm .output
+            result=$?
+            if [ $result -ne 0 ]; then
+              slack -s error -m "Failed to upload new release!" -f .output -T 5
+              exit 1
+            fi
+            echo "Publishing new release..."
+            hc-releases publish > .output 2>&1 &
+            pid=$!
+            until [ -f .output ]; do
+              sleep 0.1
+            done
+            tail -f --quiet --pid $pid .output
+            wait $pid
+            rm .output
+            result=$?
+            if [ $result -ne 0 ]; then
+              slack -s error -m "Failed to publish release!" -f .output -T 5
+              exit 1
+            fi
+            slack -m "New Vagrant release has been published! - *${CIRCLE_TAG}*"
   substrate_centos-6:
     environment:
       <<: *ENVIRONMENT
