.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -61,6 +61,77 @@ reference:
         name: Clean packet guests
         when: on_fail
         command: *CLEANUP
+    upload_substrates: &UPLOAD_SUBSTRATES
+      run:
+        name: Upload substrates
+        command: |
+          set +e
+          sha=$(git rev-parse --short "${CIRCLE_SHA1}")
+          s3_dst="${ASSETS_PRIVATE_BUCKET}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${sha}/"
+          mkdir -p substrate-assets
+          pushd substrate-assets
+          ls -lh
+          uploads=""
+          for file in *; do
+            if [[ "${file}" = "stub-"* ]]; then
+              echo "Skipping ${file} since it is a stub"
+              continue
+            fi
+            aws s3 ls "${s3_dst}${file}"
+            if [ $? -ne 0 ]; then
+              aws s3 cp "${file}" "${s3_dst}" > /tmp/cmd-output 2>&1
+              result=$?
+              cat /tmp/cmd-output
+              if [ $result -ne 0 ]; then
+                slack -s error -m "Failed to upload substrate asset \`${file}\`" -f /tmp/cmd-output
+                exit $result
+              fi
+              uploads="${uploads}\n${file}"
+            fi
+          done
+          if [ "${uploads}" != "" ]; then
+            echo -e "New substrate assets uploaded\n${uploads}"
+          fi
+    upload_assets: &UPLOAD_ASSETS
+      run:
+        name: Upload assets
+        command: |
+          set +e
+          if [ "${CIRCLE_TAG}" != "" ]; then
+            if [[ "${CIRCLE_TAG" = *"+"* ]; then
+              s3_dst="${ASSETS_PRIVATE_LONGTERM}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_TAG}/"
+            else
+              s3_dst="${ASSETS_PRIVATE_BUCKET}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_TAG}/"
+            fi
+          else
+            s3_dst="${ASSETS_PRIVATE_LONGTERM}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}/"
+          fi
+          mkdir -p assets
+          pushd ./assets
+          ls -lh
+          uploads=""
+          for file in * ; do
+            echo "Checking file: ${file}"
+            if [[ "${file}" = "stub-"* ]]; then
+              echo "Skipping ${file} since it is a stub"
+              continue
+            fi
+            aws s3 ls "${s3_dst}${file}"
+            if [ $? -ne 0 ]; then
+              aws s3 cp "${file}" "${s3_dst}" > /tmp/cmd-output 2>&1
+              result=$?
+              cat /tmp/cmd-output
+              if [ $result -ne 0 ]; then
+                slack -s error -m "Failed to upload installer asset \`${file}\`" -f /tmp/cmd-output
+                exit 1
+              fi
+              uploads="${uploads}\n${file}"
+            fi
+          done
+          if [ "${uploads}" != "" ]; then
+            slack -m "New installer assets available:\n\n${uploads}\n\n> ${s3_dst}"
+          fi
+          exit
     substrate: &SUBSTRATE
       docker: *builder
       steps:
@@ -107,10 +178,7 @@ reference:
                 slack -s error -m "Failed to build Vagrant substrate - ${CIRCLE_JOB}" -f /tmp/cmd-output -T 10
               fi
               exit $result
-        - persist_to_workspace:
-            root: .
-            paths:
-              - ./substrate-assets/*
+        - *UPLOAD_SUBSTRATES
         - *CLEANUP_STEP
     package: &PACKAGE
       docker: *builder
@@ -159,57 +227,8 @@ reference:
                 slack -s error -m "Failed to build Vagrant installer packages" -f /tmp/cmd-output -T 10
               fi
               exit $result
-        - persist_to_workspace:
-            root: .
-            paths:
-              - ./assets/*
+        - *UPLOAD_ASSETS
         - *CLEANUP_STEP
-    upload: &UPLOAD
-      environment:
-        <<: *ENVIRONMENT
-      docker: *builder
-      steps:
-        - attach_workspace:
-            at: .
-        - run:
-            name: Upload assets
-            command: |
-              set +e
-              if [ "${CIRCLE_TAG}" != "" ]; then
-                if [[ "${CIRCLE_TAG" = *"+"* ]; then
-                  s3_dst="${ASSETS_PRIVATE_LONGTERM}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_TAG}/"
-                else
-                  s3_dst="${ASSETS_PRIVATE_BUCKET}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_TAG}/"
-                fi
-              else
-                s3_dst="${ASSETS_PRIVATE_LONGTERM}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}/"
-              fi
-              mkdir -p assets
-              pushd ./assets
-              ls -lh
-              uploads=""
-              for file in * ; do
-                echo "Checking file: ${file}"
-                if [[ "${file}" = "stub-"* ]]; then
-                  echo "Skipping ${file} since it is a stub"
-                  continue
-                fi
-                aws s3 ls "${s3_dst}${file}"
-                if [ $? -ne 0 ]; then
-                  aws s3 cp "${file}" "${s3_dst}" > /tmp/cmd-output 2>&1
-                  result=$?
-                  cat /tmp/cmd-output
-                  if [ $result -ne 0 ]; then
-                    slack -s error -m "Failed to upload installer asset \`${file}\`" -f /tmp/cmd-output
-                    exit 1
-                  fi
-                  uploads="${uploads}\n${file}"
-                fi
-              done
-              if [ "${uploads}" != "" ]; then
-                slack -m "New installer assets available:\n\n${uploads}\n\n> ${s3_dst}"
-              fi
-              exit
 jobs:
   load_gem:
     environment:
@@ -538,11 +557,8 @@ jobs:
             packet-exec run -ssh-key /tmp/packet-key -upload -download "./pkg/dist/*SHA256SUMS*:./assets" -- ./scripts/sign.sh ${VERSION}
             mv ./assets/* ../assets/
             ls -l ../assets
+      - *UPLOAD_ASSETS
       - *CLEANUP_STEP
-      - persist_to_workspace:
-          root: .
-          paths:
-            - ./assets/*
   release_packages:
     environment:
       <<: *ENVIRONMENT
@@ -665,48 +681,6 @@ jobs:
       <<: *ENVIRONMENT
       PKT_VAGRANT_ONLY_BOXES: win-7
     <<: *PACKAGE
-  upload_substrates:
-    environment:
-      <<: *ENVIRONMENT
-    docker: *builder
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - run:
-          name: Upload substrates
-          command: |
-            set +e
-            sha=$(git rev-parse --short "${CIRCLE_SHA1}")
-            s3_dst="${ASSETS_PRIVATE_BUCKET}/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${sha}/"
-            mkdir -p substrate-assets
-            pushd substrate-assets
-            ls -lh
-            uploads=""
-            for file in *; do
-              if [[ "${file}" = "stub-"* ]]; then
-                echo "Skipping ${file} since it is a stub"
-                continue
-              fi
-              aws s3 ls "${s3_dst}${file}"
-              if [ $? -ne 0 ]; then
-                aws s3 cp "${file}" "${s3_dst}" > /tmp/cmd-output 2>&1
-                result=$?
-                cat /tmp/cmd-output
-                if [ $result -ne 0 ]; then
-                  slack -s error -m "Failed to upload substrate asset \`${file}\`" -f /tmp/cmd-output
-                  exit $result
-                fi
-                uploads="${uploads}\n${file}"
-              fi
-            done
-            if [ "${uploads}" != "" ]; then
-              echo -e "New substrate assets uploaded\n${uploads}"
-            fi
-  upload_packages:
-    <<: *UPLOAD
-  upload_shasums:
-    <<: *UPLOAD
   prerelease_publish:
     environment:
       <<: *ENVIRONMENT
@@ -839,27 +813,6 @@ workflows:
             - substrate_ubuntu-14.04-i386
             - substrate_ubuntu-14.04
             - substrate_win-7
-      - upload_substrates:
-          <<: *DEFAULT_WORKFLOW
-          requires:
-            - substrate_centos-6
-            - substrate_centos-6-i386
-            - substrate_osx-10.9
-            - substrate_ubuntu-14.04-i386
-            - substrate_ubuntu-14.04
-            - substrate_win-7
-      - upload_packages:
-          <<: *DEFAULT_WORKFLOW
-          requires:
-            - package_appimage
-            - package_archlinux
-            - package_centos-6
-            - package_centos-6-i386
-            - package_osx-10.9
-            - package_ubuntu-14.04
-            - package_ubuntu-14.04-i386
-            - package_win-7
-            - secrets_and_cleaner
       - clean_guests:
           <<: *DEFAULT_WORKFLOW
           requires:
@@ -882,10 +835,6 @@ workflows:
             - package_ubuntu-14.04
             - package_ubuntu-14.04-i386
             - package_win-7
-      - upload_shasums:
-          <<: *RELEASE_WORKFLOW
-          requires:
-            - preapproval_notification
       - approve_release:
           <<: *RELEASE_WORKFLOW
           type: approval
@@ -902,4 +851,11 @@ workflows:
       - prerelease_publish:
           <<: *PRERELEASE_WORKFLOW
           requires:
-            - upload_packages
+            - package_appimage
+            - package_archlinux
+            - package_centos-6
+            - package_centos-6-i386
+            - package_osx-10.9
+            - package_ubuntu-14.04
+            - package_ubuntu-14.04-i386
+            - package_win-7
