.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -7,6 +7,7 @@ reference:
           username: $QUAY_USERNAME
           password: $QUAY_PASSWORD
   environment: &ENVIRONMENT
+    TEST_VAR: "${CIRCLE_BUILD_NUM} - ${CIRCLE_WORKFLOW_ID}"
     SLACK_USERNAME: Vagrant
     SLACK_ICON: https://avatars.slack-edge.com/2017-10-17/257000837696_070f98107cdacc0486f6_36.png
     SLACK_TITLE: Vagrant Packaging
@@ -22,6 +23,13 @@ reference:
       filters:
         branches:
           ignore: master
+        tags:
+          only: /.*/
+    release_workflow: &RELEASE_WORKFLOW
+      context: vagrant-test
+      filters:
+        branches:
+          ignore: /.*/
         tags:
           only: /.*/
     cleanup: &CLEANUP |-
@@ -91,7 +99,9 @@ reference:
                 chmod 600 /tmp/packet-key
                 export PKT_VAGRANT_BUILD_TYPE="substrate"
                 export PACKET_EXEC_REMOTE_DIRECTORY="${CIRCLE_WORKFLOW_ID}"
-                packet-exec run -ssh-key /tmp/packet-key -download "./substrate-assets/*:./substrate-assets" -- ./.runner-vmware.sh > /tmp/cmd-output 2>&1 &
+                pkg_dir="${CIRCLE_BUILD_NUM}"
+                export PKT_VAGRANT_INSTALLER_VAGRANT_SUBSTRATE_OUTPUT_DIR="${pkg_dir}"
+                packet-exec run -ssh-key /tmp/packet-key -download "./${pkg_dir}/*:./substrate-assets" -- ./.runner-vmware.sh > /tmp/cmd-output 2>&1 &
                 pid=$!
                 until [ -f /tmp/cmd-output ]; do
                   sleep 0.1
@@ -186,6 +196,16 @@ reference:
               exit
         - *CLEANUP_STEP
 jobs:
+  tester:
+    environment:
+      <<: *ENVIRONMENT
+    docker: *packet_exec
+    steps:
+      - run:
+          name: Test Job
+          command: |
+            set +e
+            echo "Value: ${TEST_VAR}"
   load_gem:
     environment:
       <<: *ENVIRONMENT
@@ -323,11 +343,85 @@ jobs:
     environment:
       <<: *ENVIRONMENT
     docker: *packet_exec
-    when: always
     steps:
       - run:
           name: Clean packet guests
           command: *CLEANUP
+  sign_packages:
+    environment:
+      <<: *ENVIRONMENT
+    docker: *packet_exec
+    steps:
+      - checkout
+      - attach_workspace:
+          at: .
+      - run:
+          name: Sign packages
+          command: |
+            set +e
+            echo -e -n "${PACKET_SSH_KEY}" > /tmp/packet-key
+            chmod 600 /tmp/packet-key
+            rm assets/substrate*
+            git clone https://github.com/hashicorp/vagrant vagrant
+            mv assets/* vagrant/pkg/dist/
+            pushd vagrant
+            VERSION="${CIRCLE_TAG##v}"
+            if [ "${VERSION}" == "" ]; then
+              slack -s error -m "Failed to determine package version for signing"
+              exit 1
+            fi
+            unset PACKET_EXEC_PERSIST
+            export PACKET_EXEC_PRE_BUILTINS="LoadSecrets"
+            export PACKET_EXEC_REMOTE_DIRECTORY="${CIRCLE_JOB_NUM}"
+            packet-exec run -ssh-key /tmp/packet-key -upload -download "./pkg/dist/*SHA256SUMS*:./assets" -- ./scripts/sign.sh ${VERSION}
+      - *CLEANUP_STEP
+      - persist_to_workspace:
+          root: .
+          paths:
+            - ./assets/*SHA256SUMS*
+  release_packages:
+    environment:
+      <<: *ENVIRONMENT
+      docker: *packet_exec
+      steps:
+        - attach_workspace:
+            at: .
+        - run:
+            name: Release Vagrant Packages
+            command: |
+              set +e
+              rm -f ./assets/substrate*
+              export AWS_ACCESS_KEY_ID="${AWS_RELEASE_ID}"
+              export AWS_SECRET_ACCESS_KEY="${AWS_RELEASE_KEY}"
+              echo "Uploading to the releases site..."
+              hc-releases upload ./assets > .output 2>&1 &
+              pid=$!
+              until [ -f .output ]; do
+                sleep 0.1
+              done
+              tail -f --quiet --pid $pid .output
+              wait $pid
+              rm .output
+              result=$?
+              if [ $result -ne 0 ]; then
+                slack -s error -m "Failed to upload new release!" -f .output -T 5
+                exit 1
+              fi
+              echo "Publishing new release..."
+              hc-releases publish > .output 2>&1 &
+              pid=$!
+              until [ -f .output ]; do
+                sleep 0.1
+              done
+              tail -f --quiet --pid $pid .output
+              wait $pid
+              rm .output
+              result=$?
+              if [ $result -ne 0 ]; then
+                slack -s error -m "Failed to publish release!" -f .output -T 5
+                exit 1
+              fi
+              slack -m "New Vagrant release has been published! - *${CIRCLE_TAG}*"
   substrate_centos-6:
     environment:
       <<: *ENVIRONMENT
@@ -401,6 +495,8 @@ jobs:
   upload_substrates:
     <<: *UPLOAD
   upload_packages:
+    <<: *UPLOAD
+  upload_shasums:
     <<: *UPLOAD
 workflows:
   version: 2
@@ -522,3 +618,30 @@ workflows:
             - package_ubuntu-14.04
             - package_ubuntu-14.04-i386
             - package_win-7
+      - sign_packages:
+          <<: *RELEASE_WORKFLOW
+          requires:
+            - package_appimage
+            - package_archlinux
+            - package_centos-6
+            - package_centos-6-i386
+            - package_osx-10.9
+            - package_ubuntu-14.04
+            - package_ubuntu-14.04-i386
+            - package_win-7
+      - upload_shasums:
+          <<: *RELEASE_WORKFLOW
+          requires:
+            - sign_packages
+      - approve_release:
+          type: approval
+          requires:
+            - sign_packages
+      - release_packages:
+          <<: *RELEASE_WORKFLOW
+          requires:
+            - approve_release
+      - tester:
+          filters:
+            branches:
+              only: master
